--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LootSpace369/LSPlaceholderAPI
build-by-default: true
branches:
- main
projects:
  LSPlaceholderAPI:
    path: ""
    model: virion
    type: library
...
